# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CategoriaRegistro.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RegistroCategoria(object):
    def setupUi(self, RegistroCategoria):
        RegistroCategoria.setObjectName("RegistroCategoria")
        RegistroCategoria.resize(587, 393)
        self.line_4 = QtWidgets.QFrame(RegistroCategoria)
        self.line_4.setGeometry(QtCore.QRect(560, 190, 20, 121))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_9 = QtWidgets.QFrame(RegistroCategoria)
        self.line_9.setGeometry(QtCore.QRect(20, 10, 551, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_13 = QtWidgets.QFrame(RegistroCategoria)
        self.line_13.setGeometry(QtCore.QRect(560, 20, 20, 61))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_3 = QtWidgets.QLabel(RegistroCategoria)
        self.label_3.setGeometry(QtCore.QRect(150, 30, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_8 = QtWidgets.QFrame(RegistroCategoria)
        self.line_8.setGeometry(QtCore.QRect(20, 180, 551, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayoutWidget = QtWidgets.QWidget(RegistroCategoria)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 90, 491, 84))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("recursos/logo.png"))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_2.addWidget(self.label_5, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_2.addWidget(self.label_11, QtCore.Qt.AlignHCenter)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(RegistroCategoria)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 200, 511, 91))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        spacerItem = QtWidgets.QSpacerItem(30, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem)
        self.edit_codigoCategoria = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_codigoCategoria.setObjectName("edit_codigoCategoria")
        self.horizontalLayout_11.addWidget(self.edit_codigoCategoria)
        spacerItem1 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        spacerItem2 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.edit_nombreCategoria = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_nombreCategoria.setObjectName("edit_nombreCategoria")
        self.horizontalLayout_11.addWidget(self.edit_nombreCategoria)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.edit_descripcionCategoria = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_descripcionCategoria.setObjectName("edit_descripcionCategoria")
        self.horizontalLayout_12.addWidget(self.edit_descripcionCategoria)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.label_22 = QtWidgets.QLabel(RegistroCategoria)
        self.label_22.setGeometry(QtCore.QRect(510, 0, 101, 101))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("recursos/iconoregistrar.png"))
        self.label_22.setObjectName("label_22")
        self.line_5 = QtWidgets.QFrame(RegistroCategoria)
        self.line_5.setGeometry(QtCore.QRect(10, 80, 20, 101))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_10 = QtWidgets.QFrame(RegistroCategoria)
        self.line_10.setGeometry(QtCore.QRect(20, 300, 551, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_6 = QtWidgets.QFrame(RegistroCategoria)
        self.line_6.setGeometry(QtCore.QRect(20, 70, 551, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(RegistroCategoria)
        self.line_7.setGeometry(QtCore.QRect(20, 170, 551, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_11 = QtWidgets.QFrame(RegistroCategoria)
        self.line_11.setGeometry(QtCore.QRect(560, 80, 20, 101))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(RegistroCategoria)
        self.line_12.setGeometry(QtCore.QRect(10, 20, 20, 61))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_3 = QtWidgets.QFrame(RegistroCategoria)
        self.line_3.setGeometry(QtCore.QRect(10, 190, 20, 121))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(RegistroCategoria)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(350, 340, 221, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.boton_Siguiente_Datos = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Siguiente_Datos.setIcon(icon)
        self.boton_Siguiente_Datos.setObjectName("boton_Siguiente_Datos")
        self.horizontalLayout_5.addWidget(self.boton_Siguiente_Datos)
        self.boton_Cancelar_Datos = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recursos/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Cancelar_Datos.setIcon(icon1)
        self.boton_Cancelar_Datos.setObjectName("boton_Cancelar_Datos")
        self.horizontalLayout_5.addWidget(self.boton_Cancelar_Datos)

        self.retranslateUi(RegistroCategoria)
        QtCore.QMetaObject.connectSlotsByName(RegistroCategoria)

    def retranslateUi(self, RegistroCategoria):
        _translate = QtCore.QCoreApplication.translate
        RegistroCategoria.setWindowTitle(_translate("RegistroCategoria", "Registro de categoría"))
        self.label_3.setText(_translate("RegistroCategoria", "Ingreso de categoría"))
        self.label_5.setText(_translate("RegistroCategoria", "MODO MUEBLERÍA COMPAÑÍA LTDA"))
        self.label_9.setText(_translate("RegistroCategoria", "Av. 12 de Abril y Av. Loja"))
        self.label_11.setText(_translate("RegistroCategoria", "Cuenca - Ecuador"))
        self.label_16.setText(_translate("RegistroCategoria", "Telf: 0991538711"))
        self.label_19.setText(_translate("RegistroCategoria", "Código.:"))
        self.label_20.setText(_translate("RegistroCategoria", "Nombre.:"))
        self.label_21.setText(_translate("RegistroCategoria", "Descripción.: "))
        self.boton_Siguiente_Datos.setText(_translate("RegistroCategoria", "Ingresar"))
        self.boton_Cancelar_Datos.setText(_translate("RegistroCategoria", "Cancelar"))

