# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EliminarProducto.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BorrarProducto(object):
    def setupUi(self, BorrarProducto):
        BorrarProducto.setObjectName("BorrarProducto")
        BorrarProducto.resize(602, 595)
        BorrarProducto.setMinimumSize(QtCore.QSize(602, 595))
        BorrarProducto.setMaximumSize(QtCore.QSize(602, 595))
        self.label_3 = QtWidgets.QLabel(BorrarProducto)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_10 = QtWidgets.QFrame(BorrarProducto)
        self.line_10.setGeometry(QtCore.QRect(30, 570, 551, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayoutWidget = QtWidgets.QWidget(BorrarProducto)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 90, 491, 84))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("recursos/logo.png"))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16, QtCore.Qt.AlignHCenter)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_9.addWidget(self.label_17, QtCore.Qt.AlignHCenter)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_9.addWidget(self.label_19, QtCore.Qt.AlignHCenter)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_9.addWidget(self.label_20)
        self.horizontalLayout_10.addLayout(self.verticalLayout_9)
        self.line_14 = QtWidgets.QFrame(BorrarProducto)
        self.line_14.setGeometry(QtCore.QRect(30, 240, 551, 21))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.tabla_productos = QtWidgets.QTableWidget(BorrarProducto)
        self.tabla_productos.setGeometry(QtCore.QRect(40, 260, 531, 171))
        self.tabla_productos.setAutoFillBackground(False)
        self.tabla_productos.setLineWidth(1)
        self.tabla_productos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_productos.setAlternatingRowColors(True)
        self.tabla_productos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_productos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_productos.setShowGrid(True)
        self.tabla_productos.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_productos.setRowCount(10)
        self.tabla_productos.setColumnCount(4)
        self.tabla_productos.setObjectName("tabla_productos")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos.setHorizontalHeaderItem(3, item)
        self.tabla_productos.horizontalHeader().setDefaultSectionSize(122)
        self.line_15 = QtWidgets.QFrame(BorrarProducto)
        self.line_15.setGeometry(QtCore.QRect(30, 430, 551, 21))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_34 = QtWidgets.QLabel(BorrarProducto)
        self.label_34.setGeometry(QtCore.QRect(50, 210, 231, 21))
        self.label_34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_34.setObjectName("label_34")
        self.layoutWidget = QtWidgets.QWidget(BorrarProducto)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 210, 251, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_11.addWidget(self.label_36)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setMaxVisibleItems(50)
        self.comboBox.setIconSize(QtCore.QSize(16, 16))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox)
        self.line_9 = QtWidgets.QFrame(BorrarProducto)
        self.line_9.setGeometry(QtCore.QRect(30, 10, 551, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_3 = QtWidgets.QFrame(BorrarProducto)
        self.line_3.setGeometry(QtCore.QRect(20, 190, 20, 391))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_8 = QtWidgets.QFrame(BorrarProducto)
        self.line_8.setGeometry(QtCore.QRect(30, 180, 551, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_6 = QtWidgets.QFrame(BorrarProducto)
        self.line_6.setGeometry(QtCore.QRect(30, 70, 551, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(BorrarProducto)
        self.line_7.setGeometry(QtCore.QRect(30, 170, 551, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_4 = QtWidgets.QFrame(BorrarProducto)
        self.line_4.setGeometry(QtCore.QRect(570, 190, 20, 391))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_13 = QtWidgets.QFrame(BorrarProducto)
        self.line_13.setGeometry(QtCore.QRect(570, 20, 20, 61))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_33 = QtWidgets.QLabel(BorrarProducto)
        self.label_33.setGeometry(QtCore.QRect(520, 0, 101, 101))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("recursos/iconoadministrar.png"))
        self.label_33.setObjectName("label_33")
        self.line_5 = QtWidgets.QFrame(BorrarProducto)
        self.line_5.setGeometry(QtCore.QRect(20, 80, 20, 101))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_12 = QtWidgets.QFrame(BorrarProducto)
        self.line_12.setGeometry(QtCore.QRect(20, 20, 20, 61))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_11 = QtWidgets.QFrame(BorrarProducto)
        self.line_11.setGeometry(QtCore.QRect(570, 80, 20, 101))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_35 = QtWidgets.QLabel(BorrarProducto)
        self.label_35.setGeometry(QtCore.QRect(160, 510, 201, 21))
        self.label_35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_35.setObjectName("label_35")
        self.text_codigo_eliminar_producto = QtWidgets.QLabel(BorrarProducto)
        self.text_codigo_eliminar_producto.setGeometry(QtCore.QRect(220, 540, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.text_codigo_eliminar_producto.setFont(font)
        self.text_codigo_eliminar_producto.setObjectName("text_codigo_eliminar_producto")
        self.label_31 = QtWidgets.QLabel(BorrarProducto)
        self.label_31.setGeometry(QtCore.QRect(160, 460, 181, 21))
        self.label_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_31.setObjectName("label_31")
        self.text_nombre_producto = QtWidgets.QLabel(BorrarProducto)
        self.text_nombre_producto.setGeometry(QtCore.QRect(220, 480, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.text_nombre_producto.setFont(font)
        self.text_nombre_producto.setObjectName("text_nombre_producto")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(BorrarProducto)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(400, 490, 167, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.boton_eliminar_producto = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.boton_eliminar_producto.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_eliminar_producto.setIcon(icon)
        self.boton_eliminar_producto.setIconSize(QtCore.QSize(70, 60))
        self.boton_eliminar_producto.setObjectName("boton_eliminar_producto")
        self.horizontalLayout_17.addWidget(self.boton_eliminar_producto)
        self.boton_cancelar_producto = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.boton_cancelar_producto.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recursos/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_cancelar_producto.setIcon(icon1)
        self.boton_cancelar_producto.setIconSize(QtCore.QSize(65, 60))
        self.boton_cancelar_producto.setObjectName("boton_cancelar_producto")
        self.horizontalLayout_17.addWidget(self.boton_cancelar_producto)
        self.botonSeleccionar = QtWidgets.QPushButton(BorrarProducto)
        self.botonSeleccionar.setGeometry(QtCore.QRect(60, 480, 67, 68))
        self.botonSeleccionar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("recursos/1-Touch-with-pressure-of-one-finger-of-the-hand-on-a-circular-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonSeleccionar.setIcon(icon2)
        self.botonSeleccionar.setIconSize(QtCore.QSize(40, 60))
        self.botonSeleccionar.setObjectName("botonSeleccionar")

        self.retranslateUi(BorrarProducto)
        QtCore.QMetaObject.connectSlotsByName(BorrarProducto)

    def retranslateUi(self, BorrarProducto):
        _translate = QtCore.QCoreApplication.translate
        BorrarProducto.setWindowTitle(_translate("BorrarProducto", "Eliminar Producto"))
        self.label_3.setText(_translate("BorrarProducto", "Borrado de Producto"))
        self.label_16.setText(_translate("BorrarProducto", "MODO MUEBLERÍA COMPAÑÍA LTDA"))
        self.label_17.setText(_translate("BorrarProducto", "Av. 12 de Abril y Av. Loja"))
        self.label_19.setText(_translate("BorrarProducto", "Cuenca - Ecuador"))
        self.label_20.setText(_translate("BorrarProducto", "Telf: 0991538711"))
        item = self.tabla_productos.horizontalHeaderItem(0)
        item.setText(_translate("BorrarProducto", "Valor Unit."))
        item = self.tabla_productos.horizontalHeaderItem(1)
        item.setText(_translate("BorrarProducto", "Código"))
        item = self.tabla_productos.horizontalHeaderItem(2)
        item.setText(_translate("BorrarProducto", "Producto"))
        item = self.tabla_productos.horizontalHeaderItem(3)
        item.setText(_translate("BorrarProducto", "Descripción"))
        self.label_34.setText(_translate("BorrarProducto", "Seleccione la categoría del producto a eliminar"))
        self.label_36.setText(_translate("BorrarProducto", "Categoría:"))
        self.comboBox.setItemText(0, _translate("BorrarProducto", "Todas"))
        self.label_35.setText(_translate("BorrarProducto", "El código del producto selecionado es.:"))
        self.text_codigo_eliminar_producto.setText(_translate("BorrarProducto", "\"Codigo Producto\""))
        self.label_31.setText(_translate("BorrarProducto", "El producto seleccionado es.:"))
        self.text_nombre_producto.setText(_translate("BorrarProducto", "\"Producto Seleccionado\""))
        self.boton_eliminar_producto.setToolTip(_translate("BorrarProducto", "Eliminar producto"))
        self.boton_cancelar_producto.setToolTip(_translate("BorrarProducto", "Cancelar"))
        self.botonSeleccionar.setToolTip(_translate("BorrarProducto", "Seleccionar producto para eliminar"))

