# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FacturaCliente.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Factura(object):
    def setupUi(self, Factura):
        Factura.setObjectName("Factura")
        Factura.resize(613, 611)
        Factura.setMinimumSize(QtCore.QSize(613, 611))
        Factura.setMaximumSize(QtCore.QSize(613, 611))
        Factura.setAutoFillBackground(False)
        Factura.setInputMethodHints(QtCore.Qt.ImhNone)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Factura)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 20, 491, 84))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("recursos/logo.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6, QtCore.Qt.AlignHCenter)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Factura)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 130, 564, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.text_NumFacturaCliente = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.text_NumFacturaCliente.setFont(font)
        self.text_NumFacturaCliente.setObjectName("text_NumFacturaCliente")
        self.horizontalLayout_2.addWidget(self.text_NumFacturaCliente)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.text_FechaFacturaCliente = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.text_FechaFacturaCliente.setFont(font)
        self.text_FechaFacturaCliente.setObjectName("text_FechaFacturaCliente")
        self.horizontalLayout_2.addWidget(self.text_FechaFacturaCliente)
        self.tabla_productos = QtWidgets.QTableWidget(Factura)
        self.tabla_productos.setGeometry(QtCore.QRect(20, 300, 571, 181))
        self.tabla_productos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tabla_productos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_productos.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tabla_productos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_productos.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_productos.setRowCount(10)
        self.tabla_productos.setColumnCount(5)
        self.tabla_productos.setObjectName("tabla_productos")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos.setHorizontalHeaderItem(4, item)
        self.tabla_productos.horizontalHeader().setDefaultSectionSize(106)
        self.tabla_productos.verticalHeader().setDefaultSectionSize(30)
        self.tabla_productos.verticalHeader().setMinimumSectionSize(23)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Factura)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 500, 208, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.text_SubtotalFacturaCliente = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_SubtotalFacturaCliente.setFont(font)
        self.text_SubtotalFacturaCliente.setAlignment(QtCore.Qt.AlignCenter)
        self.text_SubtotalFacturaCliente.setContentsMargins(0, 0, 0, 0)
        self.text_SubtotalFacturaCliente.setObjectName("text_SubtotalFacturaCliente")
        self.horizontalLayout_5.addWidget(self.text_SubtotalFacturaCliente)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.text_IVAFacturaCliente = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_IVAFacturaCliente.setFont(font)
        self.text_IVAFacturaCliente.setAlignment(QtCore.Qt.AlignCenter)
        self.text_IVAFacturaCliente.setContentsMargins(0, 0, 0, 0)
        self.text_IVAFacturaCliente.setObjectName("text_IVAFacturaCliente")
        self.horizontalLayout_6.addWidget(self.text_IVAFacturaCliente)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.text_TotalFacturaCliente = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_TotalFacturaCliente.setFont(font)
        self.text_TotalFacturaCliente.setAlignment(QtCore.Qt.AlignCenter)
        self.text_TotalFacturaCliente.setContentsMargins(0, 0, 0, 0)
        self.text_TotalFacturaCliente.setObjectName("text_TotalFacturaCliente")
        self.horizontalLayout_7.addWidget(self.text_TotalFacturaCliente)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(Factura)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(530, 510, 64, 75))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 65))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Factura)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(110, 160, 461, 131))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.text_nombreCliente = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.text_nombreCliente.setFont(font)
        self.text_nombreCliente.setObjectName("text_nombreCliente")
        self.verticalLayout_4.addWidget(self.text_nombreCliente)
        self.text_direccionCliente = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.text_direccionCliente.setFont(font)
        self.text_direccionCliente.setObjectName("text_direccionCliente")
        self.verticalLayout_4.addWidget(self.text_direccionCliente)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.text_CedulaCliente = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.text_CedulaCliente.setFont(font)
        self.text_CedulaCliente.setObjectName("text_CedulaCliente")
        self.horizontalLayout_4.addWidget(self.text_CedulaCliente)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.text_telefonoCliente = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.text_telefonoCliente.setFont(font)
        self.text_telefonoCliente.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text_telefonoCliente.setObjectName("text_telefonoCliente")
        self.horizontalLayout_4.addWidget(self.text_telefonoCliente)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Factura)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(40, 160, 71, 129))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.line = QtWidgets.QFrame(Factura)
        self.line.setGeometry(QtCore.QRect(20, 110, 571, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Factura)
        self.line_2.setGeometry(QtCore.QRect(20, 280, 571, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Factura)
        self.line_3.setGeometry(QtCore.QRect(10, 120, 20, 171))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Factura)
        self.line_4.setGeometry(QtCore.QRect(580, 120, 20, 171))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Factura)
        self.line_5.setGeometry(QtCore.QRect(20, 150, 571, 21))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Factura)
        self.line_6.setGeometry(QtCore.QRect(20, 0, 571, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Factura)
        self.line_7.setGeometry(QtCore.QRect(10, 10, 20, 101))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Factura)
        self.line_8.setGeometry(QtCore.QRect(580, 10, 21, 101))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Factura)
        self.line_9.setGeometry(QtCore.QRect(20, 100, 571, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Factura)
        self.line_10.setGeometry(QtCore.QRect(10, 490, 16, 111))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(Factura)
        self.line_11.setGeometry(QtCore.QRect(20, 480, 221, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(Factura)
        self.line_12.setGeometry(QtCore.QRect(230, 490, 21, 111))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(Factura)
        self.line_13.setGeometry(QtCore.QRect(20, 590, 221, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_8 = QtWidgets.QLabel(Factura)
        self.label_8.setGeometry(QtCore.QRect(280, 510, 221, 81))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("recursos/1.png"))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Factura)
        QtCore.QMetaObject.connectSlotsByName(Factura)

    def retranslateUi(self, Factura):
        _translate = QtCore.QCoreApplication.translate
        Factura.setWindowTitle(_translate("Factura", "Factura Cliente"))
        self.label_2.setText(_translate("Factura", "MODO MUEBLERÍA COMPAÑÍA LTDA"))
        self.label_5.setText(_translate("Factura", "Av. 12 de Abril y Av. Loja"))
        self.label_6.setText(_translate("Factura", "Cuenca - Ecuador"))
        self.label_14.setText(_translate("Factura", "Telf: 0991538711"))
        self.label_3.setText(_translate("Factura", "Factura número:"))
        self.text_NumFacturaCliente.setText(_translate("Factura", "0000001"))
        self.label_4.setText(_translate("Factura", "Fecha de emisión:"))
        self.text_FechaFacturaCliente.setText(_translate("Factura", "08/06/2017"))
        item = self.tabla_productos.horizontalHeaderItem(0)
        item.setText(_translate("Factura", "Código"))
        item = self.tabla_productos.horizontalHeaderItem(1)
        item.setText(_translate("Factura", "Producto"))
        item = self.tabla_productos.horizontalHeaderItem(2)
        item.setText(_translate("Factura", "Valor unitario"))
        item = self.tabla_productos.horizontalHeaderItem(3)
        item.setText(_translate("Factura", "Cantidad"))
        item = self.tabla_productos.horizontalHeaderItem(4)
        item.setText(_translate("Factura", "Subtotal"))
        self.label_11.setText(_translate("Factura", "Subtotal:"))
        self.text_SubtotalFacturaCliente.setText(_translate("Factura", "0.00"))
        self.label_13.setText(_translate("Factura", "SubTotal IVA-12:"))
        self.text_IVAFacturaCliente.setText(_translate("Factura", "0.00"))
        self.label_15.setText(_translate("Factura", "TOTAL:"))
        self.text_TotalFacturaCliente.setText(_translate("Factura", "0.00"))
        self.pushButton.setToolTip(_translate("Factura", "Entendido"))
        self.text_nombreCliente.setText(_translate("Factura", "Consumidor Final"))
        self.text_direccionCliente.setText(_translate("Factura", "9999999999"))
        self.text_CedulaCliente.setText(_translate("Factura", "9999999999"))
        self.label_19.setText(_translate("Factura", "Teléfono/Celular:"))
        self.text_telefonoCliente.setText(_translate("Factura", "9999999999"))
        self.label_7.setText(_translate("Factura", "Cliente:"))
        self.label_9.setText(_translate("Factura", "Dirección:"))
        self.label_17.setText(_translate("Factura", "RUC/CI:"))

