# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InformacionVentas.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_infoventas(object):
    def setupUi(self, infoventas):
        infoventas.setObjectName("infoventas")
        infoventas.resize(594, 520)
        infoventas.setMinimumSize(QtCore.QSize(594, 520))
        infoventas.setMaximumSize(QtCore.QSize(594, 520))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/casita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        infoventas.setWindowIcon(icon)
        self.label_3 = QtWidgets.QLabel(infoventas)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 211, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("recursos/logo.png"))
        self.label_3.setObjectName("label_3")
        self.tabla_ventas = QtWidgets.QTableWidget(infoventas)
        self.tabla_ventas.setGeometry(QtCore.QRect(20, 110, 551, 261))
        self.tabla_ventas.setMaximumSize(QtCore.QSize(551, 261))
        self.tabla_ventas.setAutoFillBackground(False)
        self.tabla_ventas.setLineWidth(1)
        self.tabla_ventas.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tabla_ventas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_ventas.setAlternatingRowColors(True)
        self.tabla_ventas.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tabla_ventas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_ventas.setShowGrid(True)
        self.tabla_ventas.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_ventas.setRowCount(10)
        self.tabla_ventas.setColumnCount(5)
        self.tabla_ventas.setObjectName("tabla_ventas")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_ventas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_ventas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_ventas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_ventas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_ventas.setHorizontalHeaderItem(4, item)
        self.tabla_ventas.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_ventas.horizontalHeader().setDefaultSectionSize(102)
        self.tabla_ventas.verticalHeader().setCascadingSectionResizes(False)
        self.tabla_ventas.verticalHeader().setDefaultSectionSize(35)
        self.label_2 = QtWidgets.QLabel(infoventas)
        self.label_2.setGeometry(QtCore.QRect(70, 420, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_categorias = QtWidgets.QComboBox(infoventas)
        self.comboBox_categorias.setGeometry(QtCore.QRect(210, 420, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_categorias.setFont(font)
        self.comboBox_categorias.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_categorias.setEditable(False)
        self.comboBox_categorias.setCurrentText("Todas")
        self.comboBox_categorias.setMaxVisibleItems(20)
        self.comboBox_categorias.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox_categorias.setObjectName("comboBox_categorias")
        self.comboBox_categorias.addItem("")
        self.label = QtWidgets.QLabel(infoventas)
        self.label.setGeometry(QtCore.QRect(230, 50, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(infoventas)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(510, 430, 64, 75))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.botonaceptar = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.botonaceptar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recursos/aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonaceptar.setIcon(icon1)
        self.botonaceptar.setIconSize(QtCore.QSize(50, 65))
        self.botonaceptar.setObjectName("botonaceptar")
        self.horizontalLayout_8.addWidget(self.botonaceptar)
        self.label_4 = QtWidgets.QLabel(infoventas)
        self.label_4.setGeometry(QtCore.QRect(70, 470, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_fechas = QtWidgets.QComboBox(infoventas)
        self.comboBox_fechas.setGeometry(QtCore.QRect(210, 470, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_fechas.setFont(font)
        self.comboBox_fechas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_fechas.setEditable(False)
        self.comboBox_fechas.setCurrentText("Todas")
        self.comboBox_fechas.setMaxVisibleItems(20)
        self.comboBox_fechas.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox_fechas.setObjectName("comboBox_fechas")
        self.comboBox_fechas.addItem("")
        self.label_5 = QtWidgets.QLabel(infoventas)
        self.label_5.setGeometry(QtCore.QRect(40, 380, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(infoventas)
        QtCore.QMetaObject.connectSlotsByName(infoventas)

    def retranslateUi(self, infoventas):
        _translate = QtCore.QCoreApplication.translate
        infoventas.setWindowTitle(_translate("infoventas", "Información Ventas"))
        item = self.tabla_ventas.horizontalHeaderItem(0)
        item.setText(_translate("infoventas", "Num. Factura"))
        item = self.tabla_ventas.horizontalHeaderItem(1)
        item.setText(_translate("infoventas", "Producto"))
        item = self.tabla_ventas.horizontalHeaderItem(2)
        item.setText(_translate("infoventas", "Código"))
        item = self.tabla_ventas.horizontalHeaderItem(3)
        item.setText(_translate("infoventas", "Precio"))
        item = self.tabla_ventas.horizontalHeaderItem(4)
        item.setText(_translate("infoventas", "Cantidad"))
        self.label_2.setText(_translate("infoventas", "Categoría"))
        self.comboBox_categorias.setItemText(0, _translate("infoventas", "Todas"))
        self.label.setText(_translate("infoventas", "Información de ventas realizadas"))
        self.botonaceptar.setToolTip(_translate("infoventas", "Entendido"))
        self.label_4.setText(_translate("infoventas", "Fecha de venta"))
        self.comboBox_fechas.setItemText(0, _translate("infoventas", "Todas"))
        self.label_5.setText(_translate("infoventas", "Filtrar lista por.:"))

