# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InformacionProductos.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InformacionProductos(object):
    def setupUi(self, InformacionProductos):
        InformacionProductos.setObjectName("InformacionProductos")
        InformacionProductos.resize(590, 477)
        InformacionProductos.setMinimumSize(QtCore.QSize(590, 477))
        InformacionProductos.setMaximumSize(QtCore.QSize(590, 477))
        self.tabla_productos_informacion = QtWidgets.QTableWidget(InformacionProductos)
        self.tabla_productos_informacion.setGeometry(QtCore.QRect(20, 60, 551, 261))
        self.tabla_productos_informacion.setMaximumSize(QtCore.QSize(551, 261))
        self.tabla_productos_informacion.setAutoFillBackground(False)
        self.tabla_productos_informacion.setLineWidth(1)
        self.tabla_productos_informacion.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tabla_productos_informacion.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_productos_informacion.setAlternatingRowColors(True)
        self.tabla_productos_informacion.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tabla_productos_informacion.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_productos_informacion.setShowGrid(True)
        self.tabla_productos_informacion.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_productos_informacion.setRowCount(10)
        self.tabla_productos_informacion.setColumnCount(5)
        self.tabla_productos_informacion.setObjectName("tabla_productos_informacion")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_informacion.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_informacion.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_informacion.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_informacion.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_informacion.setHorizontalHeaderItem(4, item)
        self.tabla_productos_informacion.horizontalHeader().setDefaultSectionSize(102)
        self.tabla_productos_informacion.verticalHeader().setCascadingSectionResizes(False)
        self.label = QtWidgets.QLabel(InformacionProductos)
        self.label.setGeometry(QtCore.QRect(160, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox_categorias_informacion = QtWidgets.QComboBox(InformacionProductos)
        self.comboBox_categorias_informacion.setGeometry(QtCore.QRect(200, 340, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_categorias_informacion.setFont(font)
        self.comboBox_categorias_informacion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_categorias_informacion.setEditable(False)
        self.comboBox_categorias_informacion.setCurrentText("Todas")
        self.comboBox_categorias_informacion.setMaxVisibleItems(20)
        self.comboBox_categorias_informacion.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox_categorias_informacion.setObjectName("comboBox_categorias_informacion")
        self.comboBox_categorias_informacion.addItem("")
        self.label_2 = QtWidgets.QLabel(InformacionProductos)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(InformacionProductos)
        self.label_3.setGeometry(QtCore.QRect(20, 380, 241, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("recursos/logo.png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(InformacionProductos)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(510, 400, 64, 75))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 65))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)

        self.retranslateUi(InformacionProductos)
        QtCore.QMetaObject.connectSlotsByName(InformacionProductos)

    def retranslateUi(self, InformacionProductos):
        _translate = QtCore.QCoreApplication.translate
        InformacionProductos.setWindowTitle(_translate("InformacionProductos", "Productos Resgistrados"))
        item = self.tabla_productos_informacion.horizontalHeaderItem(0)
        item.setText(_translate("InformacionProductos", "Categoría"))
        item = self.tabla_productos_informacion.horizontalHeaderItem(1)
        item.setText(_translate("InformacionProductos", "Valor unitario"))
        item = self.tabla_productos_informacion.horizontalHeaderItem(2)
        item.setText(_translate("InformacionProductos", "Código"))
        item = self.tabla_productos_informacion.horizontalHeaderItem(3)
        item.setText(_translate("InformacionProductos", "Producto"))
        item = self.tabla_productos_informacion.horizontalHeaderItem(4)
        item.setText(_translate("InformacionProductos", "Descripción"))
        self.label.setText(_translate("InformacionProductos", "Información de Productos"))
        self.comboBox_categorias_informacion.setItemText(0, _translate("InformacionProductos", "Todas"))
        self.label_2.setText(_translate("InformacionProductos", "Filtrar por categoría"))
        self.pushButton.setToolTip(_translate("InformacionProductos", "Entendido"))

