# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModificarCategoria.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ModificarCategoria(object):
    def setupUi(self, ModificarCategoria):
        ModificarCategoria.setObjectName("ModificarCategoria")
        ModificarCategoria.resize(591, 550)
        ModificarCategoria.setMinimumSize(QtCore.QSize(591, 550))
        ModificarCategoria.setMaximumSize(QtCore.QSize(591, 550))
        self.line_7 = QtWidgets.QFrame(ModificarCategoria)
        self.line_7.setGeometry(QtCore.QRect(20, 180, 551, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_3 = QtWidgets.QFrame(ModificarCategoria)
        self.line_3.setGeometry(QtCore.QRect(10, 200, 20, 251))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(ModificarCategoria)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 100, 491, 84))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("recursos/logo.png"))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13, QtCore.Qt.AlignHCenter)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15, QtCore.Qt.AlignHCenter)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.label_18)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.line_9 = QtWidgets.QFrame(ModificarCategoria)
        self.line_9.setGeometry(QtCore.QRect(20, 20, 551, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_8 = QtWidgets.QFrame(ModificarCategoria)
        self.line_8.setGeometry(QtCore.QRect(20, 190, 551, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_3 = QtWidgets.QLabel(ModificarCategoria)
        self.label_3.setGeometry(QtCore.QRect(120, 40, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_12 = QtWidgets.QFrame(ModificarCategoria)
        self.line_12.setGeometry(QtCore.QRect(10, 30, 20, 61))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_6 = QtWidgets.QFrame(ModificarCategoria)
        self.line_6.setGeometry(QtCore.QRect(20, 80, 551, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(ModificarCategoria)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(300, 320, 251, 101))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_16.addWidget(self.label_26)
        spacerItem = QtWidgets.QSpacerItem(27, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_16.addItem(spacerItem)
        self.edit_nombreCategoria = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_nombreCategoria.setObjectName("edit_nombreCategoria")
        self.horizontalLayout_16.addWidget(self.edit_nombreCategoria)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        spacerItem1 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.edit_descripcionCategoria = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_descripcionCategoria.setObjectName("edit_descripcionCategoria")
        self.horizontalLayout_18.addWidget(self.edit_descripcionCategoria)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        spacerItem2 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.line_5 = QtWidgets.QFrame(ModificarCategoria)
        self.line_5.setGeometry(QtCore.QRect(10, 90, 20, 101))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_28 = QtWidgets.QLabel(ModificarCategoria)
        self.label_28.setGeometry(QtCore.QRect(510, 10, 101, 101))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("recursos/iconoadministrar.png"))
        self.label_28.setObjectName("label_28")
        self.line_4 = QtWidgets.QFrame(ModificarCategoria)
        self.line_4.setGeometry(QtCore.QRect(560, 200, 20, 251))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_13 = QtWidgets.QFrame(ModificarCategoria)
        self.line_13.setGeometry(QtCore.QRect(560, 30, 20, 61))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_10 = QtWidgets.QFrame(ModificarCategoria)
        self.line_10.setGeometry(QtCore.QRect(20, 440, 551, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(ModificarCategoria)
        self.line_11.setGeometry(QtCore.QRect(560, 90, 20, 101))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_30 = QtWidgets.QLabel(ModificarCategoria)
        self.label_30.setGeometry(QtCore.QRect(30, 220, 221, 21))
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(ModificarCategoria)
        self.label_31.setGeometry(QtCore.QRect(300, 220, 181, 21))
        self.label_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_31.setObjectName("label_31")
        self.text_categoriaseleccionada = QtWidgets.QLabel(ModificarCategoria)
        self.text_categoriaseleccionada.setGeometry(QtCore.QRect(400, 260, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.text_categoriaseleccionada.setFont(font)
        self.text_categoriaseleccionada.setObjectName("text_categoriaseleccionada")
        self.tabla_categorias = QtWidgets.QTableWidget(ModificarCategoria)
        self.tabla_categorias.setGeometry(QtCore.QRect(30, 250, 241, 171))
        self.tabla_categorias.setAutoFillBackground(False)
        self.tabla_categorias.setLineWidth(1)
        self.tabla_categorias.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_categorias.setAlternatingRowColors(True)
        self.tabla_categorias.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_categorias.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_categorias.setShowGrid(True)
        self.tabla_categorias.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_categorias.setRowCount(10)
        self.tabla_categorias.setColumnCount(2)
        self.tabla_categorias.setObjectName("tabla_categorias")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_categorias.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_categorias.setHorizontalHeaderItem(1, item)
        self.tabla_categorias.horizontalHeader().setDefaultSectionSize(100)
        self.line_14 = QtWidgets.QFrame(ModificarCategoria)
        self.line_14.setGeometry(QtCore.QRect(280, 200, 20, 251))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(ModificarCategoria)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(430, 470, 141, 70))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.botonModificarCategoria = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.botonModificarCategoria.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/modificar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonModificarCategoria.setIcon(icon)
        self.botonModificarCategoria.setIconSize(QtCore.QSize(40, 60))
        self.botonModificarCategoria.setObjectName("botonModificarCategoria")
        self.horizontalLayout_21.addWidget(self.botonModificarCategoria)
        self.botonCancelarcategoria = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.botonCancelarcategoria.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recursos/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonCancelarcategoria.setIcon(icon1)
        self.botonCancelarcategoria.setIconSize(QtCore.QSize(40, 60))
        self.botonCancelarcategoria.setObjectName("botonCancelarcategoria")
        self.horizontalLayout_21.addWidget(self.botonCancelarcategoria)
        self.botonSeleccionar = QtWidgets.QPushButton(ModificarCategoria)
        self.botonSeleccionar.setGeometry(QtCore.QRect(120, 470, 67, 68))
        self.botonSeleccionar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("recursos/1-Touch-with-pressure-of-one-finger-of-the-hand-on-a-circular-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonSeleccionar.setIcon(icon2)
        self.botonSeleccionar.setIconSize(QtCore.QSize(40, 60))
        self.botonSeleccionar.setObjectName("botonSeleccionar")
        self.text_categoriaseleccionada_2 = QtWidgets.QLabel(ModificarCategoria)
        self.text_categoriaseleccionada_2.setGeometry(QtCore.QRect(320, 260, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.text_categoriaseleccionada_2.setFont(font)
        self.text_categoriaseleccionada_2.setObjectName("text_categoriaseleccionada_2")
        self.text_categoriaseleccionada_3 = QtWidgets.QLabel(ModificarCategoria)
        self.text_categoriaseleccionada_3.setGeometry(QtCore.QRect(320, 290, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.text_categoriaseleccionada_3.setFont(font)
        self.text_categoriaseleccionada_3.setObjectName("text_categoriaseleccionada_3")
        self.text_codigocategoriaseleccionada = QtWidgets.QLabel(ModificarCategoria)
        self.text_codigocategoriaseleccionada.setGeometry(QtCore.QRect(400, 290, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.text_codigocategoriaseleccionada.setFont(font)
        self.text_codigocategoriaseleccionada.setObjectName("text_codigocategoriaseleccionada")

        self.retranslateUi(ModificarCategoria)
        QtCore.QMetaObject.connectSlotsByName(ModificarCategoria)

    def retranslateUi(self, ModificarCategoria):
        _translate = QtCore.QCoreApplication.translate
        ModificarCategoria.setWindowTitle(_translate("ModificarCategoria", "Modificar Categoria"))
        self.label_13.setText(_translate("ModificarCategoria", "MODO MUEBLERÍA COMPAÑÍA LTDA"))
        self.label_14.setText(_translate("ModificarCategoria", "Av. 12 de Abril y Av. Loja"))
        self.label_15.setText(_translate("ModificarCategoria", "Cuenca - Ecuador"))
        self.label_18.setText(_translate("ModificarCategoria", "Telf: 0991538711"))
        self.label_3.setText(_translate("ModificarCategoria", "Modificación de Categoría"))
        self.label_26.setText(_translate("ModificarCategoria", "Nombre.:"))
        self.label_29.setText(_translate("ModificarCategoria", "Descripción.: "))
        self.label_30.setText(_translate("ModificarCategoria", "Selecciona la categoría que deseas modificar"))
        self.label_31.setText(_translate("ModificarCategoria", "Modifica los campos de la categoría.:"))
        self.text_categoriaseleccionada.setText(_translate("ModificarCategoria", "\"Categoría Seleccionada\""))
        item = self.tabla_categorias.horizontalHeaderItem(0)
        item.setText(_translate("ModificarCategoria", "Categoría"))
        item = self.tabla_categorias.horizontalHeaderItem(1)
        item.setText(_translate("ModificarCategoria", "Código"))
        self.botonModificarCategoria.setToolTip(_translate("ModificarCategoria", "Modificar"))
        self.botonCancelarcategoria.setToolTip(_translate("ModificarCategoria", "Cancelar"))
        self.botonSeleccionar.setToolTip(_translate("ModificarCategoria", "Seleccionar categoria para modificar"))
        self.text_categoriaseleccionada_2.setText(_translate("ModificarCategoria", "Categoría  :"))
        self.text_categoriaseleccionada_3.setText(_translate("ModificarCategoria", "Con código:"))
        self.text_codigocategoriaseleccionada.setText(_translate("ModificarCategoria", "\"Código\""))

