# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModificarProducto.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ModificarProducto(object):
    def setupUi(self, ModificarProducto):
        ModificarProducto.setObjectName("ModificarProducto")
        ModificarProducto.resize(588, 700)
        ModificarProducto.setMinimumSize(QtCore.QSize(588, 669))
        ModificarProducto.setMaximumSize(QtCore.QSize(588, 700))
        self.line_5 = QtWidgets.QFrame(ModificarProducto)
        self.line_5.setGeometry(QtCore.QRect(10, 80, 20, 101))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_3 = QtWidgets.QFrame(ModificarProducto)
        self.line_3.setGeometry(QtCore.QRect(10, 190, 20, 421))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_8 = QtWidgets.QFrame(ModificarProducto)
        self.line_8.setGeometry(QtCore.QRect(20, 180, 551, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayoutWidget = QtWidgets.QWidget(ModificarProducto)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 90, 491, 84))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("recursos/logo.png"))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16, QtCore.Qt.AlignHCenter)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_9.addWidget(self.label_17, QtCore.Qt.AlignHCenter)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_9.addWidget(self.label_19, QtCore.Qt.AlignHCenter)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_9.addWidget(self.label_20)
        self.horizontalLayout_10.addLayout(self.verticalLayout_9)
        self.line_14 = QtWidgets.QFrame(ModificarProducto)
        self.line_14.setGeometry(QtCore.QRect(20, 240, 551, 21))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_33 = QtWidgets.QLabel(ModificarProducto)
        self.label_33.setGeometry(QtCore.QRect(510, 0, 101, 101))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("recursos/iconoadministrar.png"))
        self.label_33.setObjectName("label_33")
        self.line_12 = QtWidgets.QFrame(ModificarProducto)
        self.line_12.setGeometry(QtCore.QRect(10, 20, 20, 61))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_3 = QtWidgets.QLabel(ModificarProducto)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_9 = QtWidgets.QFrame(ModificarProducto)
        self.line_9.setGeometry(QtCore.QRect(20, 10, 551, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_13 = QtWidgets.QFrame(ModificarProducto)
        self.line_13.setGeometry(QtCore.QRect(560, 20, 20, 61))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_34 = QtWidgets.QLabel(ModificarProducto)
        self.label_34.setGeometry(QtCore.QRect(40, 210, 231, 21))
        self.label_34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_34.setObjectName("label_34")
        self.line_4 = QtWidgets.QFrame(ModificarProducto)
        self.line_4.setGeometry(QtCore.QRect(560, 190, 20, 421))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(ModificarProducto)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(431, 620, 141, 70))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.botonModificarProducto = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.botonModificarProducto.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos//modificar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonModificarProducto.setIcon(icon)
        self.botonModificarProducto.setIconSize(QtCore.QSize(40, 60))
        self.botonModificarProducto.setObjectName("botonModificarProducto")
        self.horizontalLayout_20.addWidget(self.botonModificarProducto)
        self.botonCancelarProducto = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.botonCancelarProducto.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recursos//cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonCancelarProducto.setIcon(icon1)
        self.botonCancelarProducto.setIconSize(QtCore.QSize(40, 60))
        self.botonCancelarProducto.setObjectName("botonCancelarProducto")
        self.horizontalLayout_20.addWidget(self.botonCancelarProducto)
        self.line_6 = QtWidgets.QFrame(ModificarProducto)
        self.line_6.setGeometry(QtCore.QRect(20, 70, 551, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_11 = QtWidgets.QFrame(ModificarProducto)
        self.line_11.setGeometry(QtCore.QRect(560, 80, 20, 101))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.layoutWidget = QtWidgets.QWidget(ModificarProducto)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 210, 251, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_11.addWidget(self.label_36)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setMaxVisibleItems(50)
        self.comboBox.setIconSize(QtCore.QSize(16, 16))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox)
        self.line_7 = QtWidgets.QFrame(ModificarProducto)
        self.line_7.setGeometry(QtCore.QRect(20, 170, 551, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.tabla_productos_modificacion = QtWidgets.QTableWidget(ModificarProducto)
        self.tabla_productos_modificacion.setGeometry(QtCore.QRect(30, 260, 531, 171))
        self.tabla_productos_modificacion.setAutoFillBackground(False)
        self.tabla_productos_modificacion.setLineWidth(1)
        self.tabla_productos_modificacion.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_productos_modificacion.setAlternatingRowColors(True)
        self.tabla_productos_modificacion.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_productos_modificacion.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_productos_modificacion.setShowGrid(True)
        self.tabla_productos_modificacion.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_productos_modificacion.setRowCount(10)
        self.tabla_productos_modificacion.setColumnCount(4)
        self.tabla_productos_modificacion.setObjectName("tabla_productos_modificacion")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_modificacion.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_modificacion.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_modificacion.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_modificacion.setHorizontalHeaderItem(3, item)
        self.tabla_productos_modificacion.horizontalHeader().setDefaultSectionSize(122)
        self.line_10 = QtWidgets.QFrame(ModificarProducto)
        self.line_10.setGeometry(QtCore.QRect(20, 600, 551, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(ModificarProducto)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(250, 460, 301, 121))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_18.addWidget(self.label_28)
        spacerItem2 = QtWidgets.QSpacerItem(25, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.edit_nombre_producto_modificar = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_nombre_producto_modificar.setObjectName("edit_nombre_producto_modificar")
        self.horizontalLayout_18.addWidget(self.edit_nombre_producto_modificar)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_21.addWidget(self.label_32)
        self.edit_descripcion_producto_modificar = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_descripcion_producto_modificar.setObjectName("edit_descripcion_producto_modificar")
        self.horizontalLayout_21.addWidget(self.edit_descripcion_producto_modificar)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        spacerItem4 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        spacerItem5 = QtWidgets.QSpacerItem(13, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem5)
        self.edit_precio_producto_modificar = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_precio_producto_modificar.setObjectName("edit_precio_producto_modificar")
        self.horizontalLayout.addWidget(self.edit_precio_producto_modificar)
        spacerItem6 = QtWidgets.QSpacerItem(100, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.text_producto_seleccionado = QtWidgets.QLabel(ModificarProducto)
        self.text_producto_seleccionado.setGeometry(QtCore.QRect(70, 480, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.text_producto_seleccionado.setFont(font)
        self.text_producto_seleccionado.setObjectName("text_producto_seleccionado")
        self.label_35 = QtWidgets.QLabel(ModificarProducto)
        self.label_35.setGeometry(QtCore.QRect(40, 450, 181, 21))
        self.label_35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_35.setObjectName("label_35")
        self.line_15 = QtWidgets.QFrame(ModificarProducto)
        self.line_15.setGeometry(QtCore.QRect(20, 430, 551, 21))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.botonSeleccionarProducto = QtWidgets.QPushButton(ModificarProducto)
        self.botonSeleccionarProducto.setGeometry(QtCore.QRect(100, 520, 71, 68))
        self.botonSeleccionarProducto.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("recursos/1-Touch-with-pressure-of-one-finger-of-the-hand-on-a-circular-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonSeleccionarProducto.setIcon(icon2)
        self.botonSeleccionarProducto.setIconSize(QtCore.QSize(40, 60))
        self.botonSeleccionarProducto.setObjectName("botonSeleccionarProducto")

        self.retranslateUi(ModificarProducto)
        QtCore.QMetaObject.connectSlotsByName(ModificarProducto)

    def retranslateUi(self, ModificarProducto):
        _translate = QtCore.QCoreApplication.translate
        ModificarProducto.setWindowTitle(_translate("ModificarProducto", "Modificar datos del producto"))
        self.label_16.setText(_translate("ModificarProducto", "MODO MUEBLERÍA COMPAÑÍA LTDA"))
        self.label_17.setText(_translate("ModificarProducto", "Av. 12 de Abril y Av. Loja"))
        self.label_19.setText(_translate("ModificarProducto", "Cuenca - Ecuador"))
        self.label_20.setText(_translate("ModificarProducto", "Telf: 0991538711"))
        self.label_3.setText(_translate("ModificarProducto", "Modificación de Producto"))
        self.label_34.setText(_translate("ModificarProducto", "Seleccione la categoría del producto a modificar"))
        self.botonModificarProducto.setToolTip(_translate("ModificarProducto", "Modificar"))
        self.botonCancelarProducto.setToolTip(_translate("ModificarProducto", "Cancelar"))
        self.label_36.setText(_translate("ModificarProducto", "Categoría:"))
        self.comboBox.setItemText(0, _translate("ModificarProducto", "Todas"))
        item = self.tabla_productos_modificacion.horizontalHeaderItem(0)
        item.setText(_translate("ModificarProducto", "Valor Unit."))
        item = self.tabla_productos_modificacion.horizontalHeaderItem(1)
        item.setText(_translate("ModificarProducto", "Código"))
        item = self.tabla_productos_modificacion.horizontalHeaderItem(2)
        item.setText(_translate("ModificarProducto", "Producto"))
        item = self.tabla_productos_modificacion.horizontalHeaderItem(3)
        item.setText(_translate("ModificarProducto", "Descripción"))
        self.label_28.setText(_translate("ModificarProducto", "Nombre.:"))
        self.label_32.setText(_translate("ModificarProducto", "Descripción.: "))
        self.label_21.setText(_translate("ModificarProducto", "P.Unitario.:"))
        self.text_producto_seleccionado.setText(_translate("ModificarProducto", "\"Producto Seleccionado\""))
        self.label_35.setText(_translate("ModificarProducto", "Modifica los campos del producto.:"))
        self.botonSeleccionarProducto.setToolTip(_translate("ModificarProducto", "Seleccionar categoria para modificar"))

