# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Principal.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(594, 429)
        MainWindow.setMinimumSize(QtCore.QSize(594, 429))
        MainWindow.setMaximumSize(QtCore.QSize(594, 429))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -30, 651, 431))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("recursos/fondo.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 481, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("recursos/bienvenidos.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 531, 171))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("recursos/logo_principal.png"))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 21))
        self.menubar.setObjectName("menubar")
        self.menuInicio = QtWidgets.QMenu(self.menubar)
        self.menuInicio.setObjectName("menuInicio")
        self.menuCategor_a = QtWidgets.QMenu(self.menubar)
        self.menuCategor_a.setObjectName("menuCategor_a")
        self.menuProducto = QtWidgets.QMenu(self.menubar)
        self.menuProducto.setObjectName("menuProducto")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(35, 35))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionVer_informaci_n_de_productos = QtWidgets.QAction(MainWindow)
        self.actionVer_informaci_n_de_productos.setObjectName("actionVer_informaci_n_de_productos")
        self.actionRealizar_un_pedido = QtWidgets.QAction(MainWindow)
        self.actionRealizar_un_pedido.setObjectName("actionRealizar_un_pedido")
        self.actionAgregar = QtWidgets.QAction(MainWindow)
        self.actionAgregar.setObjectName("actionAgregar")
        self.actionModificar = QtWidgets.QAction(MainWindow)
        self.actionModificar.setObjectName("actionModificar")
        self.actionEliminar = QtWidgets.QAction(MainWindow)
        self.actionEliminar.setObjectName("actionEliminar")
        self.actionAgregar_2 = QtWidgets.QAction(MainWindow)
        self.actionAgregar_2.setObjectName("actionAgregar_2")
        self.actionModificar_2 = QtWidgets.QAction(MainWindow)
        self.actionModificar_2.setObjectName("actionModificar_2")
        self.actionEliminar_2 = QtWidgets.QAction(MainWindow)
        self.actionEliminar_2.setObjectName("actionEliminar_2")
        self.actionInformaci_n_de_ventas = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/119aac0aa4ed9b90205078ecda0550af.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInformaci_n_de_ventas.setIcon(icon)
        self.actionInformaci_n_de_ventas.setObjectName("actionInformaci_n_de_ventas")
        self.actionInformacion = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recursos/ayuda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInformacion.setIcon(icon1)
        self.actionInformacion.setObjectName("actionInformacion")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("recursos/Actions-exit-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalir.setIcon(icon2)
        self.actionSalir.setObjectName("actionSalir")
        self.actionInformaci_n_de_ventas_2 = QtWidgets.QAction(MainWindow)
        self.actionInformaci_n_de_ventas_2.setObjectName("actionInformaci_n_de_ventas_2")
        self.actionCompra = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("recursos/compra_ini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompra.setIcon(icon3)
        self.actionCompra.setObjectName("actionCompra")
        self.actionVer_Productos = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("recursos/listaproductos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVer_Productos.setIcon(icon4)
        self.actionVer_Productos.setObjectName("actionVer_Productos")
        self.menuInicio.addAction(self.actionVer_informaci_n_de_productos)
        self.menuInicio.addSeparator()
        self.menuInicio.addAction(self.actionRealizar_un_pedido)
        self.menuInicio.addSeparator()
        self.menuInicio.addAction(self.actionInformaci_n_de_ventas_2)
        self.menuInicio.addSeparator()
        self.menuCategor_a.addAction(self.actionAgregar)
        self.menuCategor_a.addSeparator()
        self.menuCategor_a.addAction(self.actionModificar)
        self.menuCategor_a.addSeparator()
        self.menuCategor_a.addAction(self.actionEliminar)
        self.menuCategor_a.addSeparator()
        self.menuProducto.addAction(self.actionAgregar_2)
        self.menuProducto.addSeparator()
        self.menuProducto.addAction(self.actionModificar_2)
        self.menuProducto.addSeparator()
        self.menuProducto.addAction(self.actionEliminar_2)
        self.menuProducto.addSeparator()
        self.menubar.addAction(self.menuInicio.menuAction())
        self.menubar.addAction(self.menuCategor_a.menuAction())
        self.menubar.addAction(self.menuProducto.menuAction())
        self.toolBar.addAction(self.actionVer_Productos)
        self.toolBar.addAction(self.actionCompra)
        self.toolBar.addAction(self.actionInformaci_n_de_ventas)
        self.toolBar.addAction(self.actionInformacion)
        self.toolBar.addAction(self.actionSalir)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Modo Mueblería"))
        self.menuInicio.setTitle(_translate("MainWindow", "Inicio"))
        self.menuCategor_a.setTitle(_translate("MainWindow", "Categoría"))
        self.menuProducto.setTitle(_translate("MainWindow", "Producto"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionVer_informaci_n_de_productos.setText(_translate("MainWindow", "Ver información de productos"))
        self.actionRealizar_un_pedido.setText(_translate("MainWindow", "Realizar un pedido"))
        self.actionAgregar.setText(_translate("MainWindow", "Agregar"))
        self.actionModificar.setText(_translate("MainWindow", "Modificar"))
        self.actionEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.actionAgregar_2.setText(_translate("MainWindow", "Agregar"))
        self.actionModificar_2.setText(_translate("MainWindow", "Modificar"))
        self.actionEliminar_2.setText(_translate("MainWindow", "Eliminar"))
        self.actionInformaci_n_de_ventas.setText(_translate("MainWindow", "Información de ventas realizadas"))
        self.actionInformaci_n_de_ventas.setToolTip(_translate("MainWindow", "Ver informaciónde ventas en una fecha"))
        self.actionInformacion.setText(_translate("MainWindow", "Acerca de"))
        self.actionInformacion.setToolTip(_translate("MainWindow", "Información de la aplicación"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setToolTip(_translate("MainWindow", "Salir de la aplicación"))
        self.actionInformaci_n_de_ventas_2.setText(_translate("MainWindow", "Información de ventas"))
        self.actionCompra.setText(_translate("MainWindow", "Compra"))
        self.actionCompra.setToolTip(_translate("MainWindow", "Realizar pedido"))
        self.actionVer_Productos.setText(_translate("MainWindow", "Ver Productos"))
        self.actionVer_Productos.setToolTip(_translate("MainWindow", "Ver informacion de productos"))

