# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProductoRegistro.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IngresoProducto(object):
    def setupUi(self, IngresoProducto):
        IngresoProducto.setObjectName("IngresoProducto")
        IngresoProducto.resize(589, 479)
        IngresoProducto.setMinimumSize(QtCore.QSize(589, 479))
        IngresoProducto.setMaximumSize(QtCore.QSize(589, 479))
        self.label_3 = QtWidgets.QLabel(IngresoProducto)
        self.label_3.setGeometry(QtCore.QRect(150, 30, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_4 = QtWidgets.QFrame(IngresoProducto)
        self.line_4.setGeometry(QtCore.QRect(560, 190, 20, 201))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_7 = QtWidgets.QFrame(IngresoProducto)
        self.line_7.setGeometry(QtCore.QRect(20, 170, 551, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_10 = QtWidgets.QFrame(IngresoProducto)
        self.line_10.setGeometry(QtCore.QRect(20, 380, 551, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayoutWidget = QtWidgets.QWidget(IngresoProducto)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 90, 491, 84))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("recursos/logo.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.label_2, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.label_7, QtCore.Qt.AlignHCenter)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_8 = QtWidgets.QFrame(IngresoProducto)
        self.line_8.setGeometry(QtCore.QRect(20, 180, 551, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(IngresoProducto)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 200, 511, 171))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setMaxVisibleItems(20)
        self.comboBox.setIconSize(QtCore.QSize(16, 16))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(55, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        spacerItem2 = QtWidgets.QSpacerItem(19, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.edit_telefono_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_telefono_3.setObjectName("edit_telefono_3")
        self.horizontalLayout_8.addWidget(self.edit_telefono_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem4 = QtWidgets.QSpacerItem(30, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.edit_cedula_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_cedula_3.setObjectName("edit_cedula_3")
        self.horizontalLayout_6.addWidget(self.edit_cedula_3)
        spacerItem5 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        spacerItem6 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.edit_telefono_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_telefono_2.setObjectName("edit_telefono_2")
        self.horizontalLayout_6.addWidget(self.edit_telefono_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.edit_cedula_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edit_cedula_4.setObjectName("edit_cedula_4")
        self.horizontalLayout_7.addWidget(self.edit_cedula_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.line_6 = QtWidgets.QFrame(IngresoProducto)
        self.line_6.setGeometry(QtCore.QRect(20, 70, 551, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(IngresoProducto)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(350, 430, 221, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.boton_Siguiente_Datos = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Siguiente_Datos.setIcon(icon)
        self.boton_Siguiente_Datos.setObjectName("boton_Siguiente_Datos")
        self.horizontalLayout_5.addWidget(self.boton_Siguiente_Datos)
        self.boton_Cancelar_Datos = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recursos/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Cancelar_Datos.setIcon(icon1)
        self.boton_Cancelar_Datos.setObjectName("boton_Cancelar_Datos")
        self.horizontalLayout_5.addWidget(self.boton_Cancelar_Datos)
        self.line_5 = QtWidgets.QFrame(IngresoProducto)
        self.line_5.setGeometry(QtCore.QRect(10, 80, 20, 101))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_3 = QtWidgets.QFrame(IngresoProducto)
        self.line_3.setGeometry(QtCore.QRect(10, 190, 20, 201))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_11 = QtWidgets.QFrame(IngresoProducto)
        self.line_11.setGeometry(QtCore.QRect(560, 80, 20, 101))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_9 = QtWidgets.QFrame(IngresoProducto)
        self.line_9.setGeometry(QtCore.QRect(20, 10, 551, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_12 = QtWidgets.QFrame(IngresoProducto)
        self.line_12.setGeometry(QtCore.QRect(10, 20, 20, 61))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(IngresoProducto)
        self.line_13.setGeometry(QtCore.QRect(560, 20, 20, 61))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_4 = QtWidgets.QLabel(IngresoProducto)
        self.label_4.setGeometry(QtCore.QRect(510, 0, 101, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("recursos/iconoregistrar.png"))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(IngresoProducto)
        QtCore.QMetaObject.connectSlotsByName(IngresoProducto)

    def retranslateUi(self, IngresoProducto):
        _translate = QtCore.QCoreApplication.translate
        IngresoProducto.setWindowTitle(_translate("IngresoProducto", "Registro de producto"))
        self.label_3.setText(_translate("IngresoProducto", "Ingreso de producto"))
        self.label_2.setText(_translate("IngresoProducto", "MODO MUEBLERÍA COMPAÑÍA LTDA"))
        self.label_6.setText(_translate("IngresoProducto", "Av. 12 de Abril y Av. Loja"))
        self.label_7.setText(_translate("IngresoProducto", "Cuenca - Ecuador"))
        self.label_12.setText(_translate("IngresoProducto", "Telf: 0991538711"))
        self.label_13.setText(_translate("IngresoProducto", "Categoría:"))
        self.comboBox.setItemText(0, _translate("IngresoProducto", "Elija una categoría"))
        self.label_15.setText(_translate("IngresoProducto", "P.Unit.:"))
        self.label_8.setText(_translate("IngresoProducto", "Código.:"))
        self.label_14.setText(_translate("IngresoProducto", "Nombre.:"))
        self.label_10.setText(_translate("IngresoProducto", "Descripción.: "))
        self.boton_Siguiente_Datos.setText(_translate("IngresoProducto", "Ingresar"))
        self.boton_Cancelar_Datos.setText(_translate("IngresoProducto", "Cancelar"))

