# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RealizarPedido.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RealizarPedido(object):
    def setupUi(self, RealizarPedido):
        RealizarPedido.setObjectName("RealizarPedido")
        RealizarPedido.resize(590, 477)
        RealizarPedido.setMinimumSize(QtCore.QSize(590, 477))
        RealizarPedido.setMaximumSize(QtCore.QSize(590, 477))
        self.comboBox_categorias_pedido = QtWidgets.QComboBox(RealizarPedido)
        self.comboBox_categorias_pedido.setGeometry(QtCore.QRect(200, 340, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_categorias_pedido.setFont(font)
        self.comboBox_categorias_pedido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_categorias_pedido.setEditable(False)
        self.comboBox_categorias_pedido.setMaxVisibleItems(15)
        self.comboBox_categorias_pedido.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox_categorias_pedido.setObjectName("comboBox_categorias_pedido")
        self.comboBox_categorias_pedido.addItem("")
        self.tabla_productos_pedido = QtWidgets.QTableWidget(RealizarPedido)
        self.tabla_productos_pedido.setGeometry(QtCore.QRect(20, 60, 551, 261))
        self.tabla_productos_pedido.setAutoFillBackground(False)
        self.tabla_productos_pedido.setLineWidth(1)
        self.tabla_productos_pedido.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_productos_pedido.setAlternatingRowColors(True)
        self.tabla_productos_pedido.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_productos_pedido.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_productos_pedido.setShowGrid(True)
        self.tabla_productos_pedido.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_productos_pedido.setRowCount(10)
        self.tabla_productos_pedido.setColumnCount(5)
        self.tabla_productos_pedido.setObjectName("tabla_productos_pedido")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_pedido.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_pedido.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_pedido.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_pedido.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_productos_pedido.setHorizontalHeaderItem(4, item)
        self.tabla_productos_pedido.horizontalHeader().setDefaultSectionSize(102)
        self.label = QtWidgets.QLabel(RealizarPedido)
        self.label.setGeometry(QtCore.QRect(140, 10, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(RealizarPedido)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(440, 360, 71, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boton_agregar = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.boton_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_agregar.setMouseTracking(False)
        self.boton_agregar.setAccessibleDescription("")
        self.boton_agregar.setAutoFillBackground(False)
        self.boton_agregar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.boton_agregar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/add-1-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_agregar.setIcon(icon)
        self.boton_agregar.setIconSize(QtCore.QSize(40, 45))
        self.boton_agregar.setShortcut("")
        self.boton_agregar.setObjectName("boton_agregar")
        self.horizontalLayout_2.addWidget(self.boton_agregar)
        self.horizontalLayoutWidget = QtWidgets.QWidget(RealizarPedido)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 430, 241, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boton_aceptar_pedido = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.boton_aceptar_pedido.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recursos/aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_aceptar_pedido.setIcon(icon1)
        self.boton_aceptar_pedido.setObjectName("boton_aceptar_pedido")
        self.horizontalLayout.addWidget(self.boton_aceptar_pedido)
        self.boton_atras_pedido = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("recursos/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_atras_pedido.setIcon(icon2)
        self.boton_atras_pedido.setObjectName("boton_atras_pedido")
        self.horizontalLayout.addWidget(self.boton_atras_pedido)
        self.label_4 = QtWidgets.QLabel(RealizarPedido)
        self.label_4.setGeometry(QtCore.QRect(420, 330, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(RealizarPedido)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(RealizarPedido)
        self.label_3.setGeometry(QtCore.QRect(60, 380, 211, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("recursos/logo.png"))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(RealizarPedido)
        QtCore.QMetaObject.connectSlotsByName(RealizarPedido)

    def retranslateUi(self, RealizarPedido):
        _translate = QtCore.QCoreApplication.translate
        RealizarPedido.setWindowTitle(_translate("RealizarPedido", "Realizar Pedido"))
        self.comboBox_categorias_pedido.setItemText(0, _translate("RealizarPedido", "Todas"))
        item = self.tabla_productos_pedido.horizontalHeaderItem(0)
        item.setText(_translate("RealizarPedido", "Categoría"))
        item = self.tabla_productos_pedido.horizontalHeaderItem(1)
        item.setText(_translate("RealizarPedido", "Valor unitario"))
        item = self.tabla_productos_pedido.horizontalHeaderItem(2)
        item.setText(_translate("RealizarPedido", "Código"))
        item = self.tabla_productos_pedido.horizontalHeaderItem(3)
        item.setText(_translate("RealizarPedido", "Producto"))
        item = self.tabla_productos_pedido.horizontalHeaderItem(4)
        item.setText(_translate("RealizarPedido", "Descripción"))
        self.label.setText(_translate("RealizarPedido", "Realizar pedido de Productos"))
        self.boton_agregar.setToolTip(_translate("RealizarPedido", "Agregar este artículo a la compra"))
        self.boton_aceptar_pedido.setText(_translate("RealizarPedido", "Finalizar Pedido"))
        self.boton_atras_pedido.setText(_translate("RealizarPedido", "Cancelar Pedido"))
        self.label_4.setText(_translate("RealizarPedido", "Agregar este artículo."))
        self.label_2.setText(_translate("RealizarPedido", "Filtrar por categoría"))

